### ISSUE TITLE
No comment tokenizer

### ISSUE THREAD

**Issue by tauren** [bkyle/obsidian-vault-statistics-plugin#22]
Notes that contain comment blocks result in `no tokenizer, section.type=comment` console.log messages

Simply add a comment block to any note and observe the console. I use comments to surround dataview fields that I don't want displayed. For example:

```
%%
projectMOC:: [[Project 1]]
%%
```

I haven't dug into the code to see if there is any statistical impact, but I wanted to report this in case comment tokenization was inadvertently missed.

**Comment by bkyle** [comment]
Good catch!  That log message indicates that the section is not handled and therefore wouldn't count toward metrics.  The fix is pretty straight forward so long as comment blocks continue to not count toward metrics.  Adding a tokenizer for comment blocks may be trickier than it sounds because there could be anything in a comment block: code, prose, a mix of both.

**Comment by tauren** [comment]
Hmmm, creates a bit of a dilemma. I can see arguments for both not counting and counting content within comments. 

I don't have a strong preference. Maybe it's best to start with the easy fix and not count content just to declutter console logs.

**Comment by bkyle** [comment]
I've committed a fix for this issue, it will be in the next release.
