### ISSUE TITLE
Feature request: Option to show all stats at once

### ISSUE THREAD

**Issue by jiri** [bkyle/obsidian-vault-statistics-plugin#6]
Considering the status bar is hardly short for space, I'd love to see all the stats at once instead of having to cycle them manually 😄

**Comment by bkyle** [comment]
You can see all of the stats at once by hovering over the status bar item.

**Comment by jiri** [comment]
I'm well aware of this, but that's not really what I suggested. My point was having the option to see the info without having to move my cursor over a tiny box in the corner of my screen.

**Comment by bkyle** [comment]
I could alter the way the status bar item is rendered so that it sets the visibility on elements for each statistic instead of what it does today.  If you don't mind writing a CSS snippet that overrides the visibility on these elements that should get you what you're after.  Would that work for you?

**Comment by jiri** [comment]
That sounds awesome :) I've been meaning to look into how obsidian plugins work -- would you be okay with me trying to implement a settings page for the plugin to set the visibility there and opening a pull request?

**Comment by bkyle** [comment]
In preparation, I've started to refactor the way statistics are displayed from updating a single element to a set of subviews, one for each statistic.  The current state of these changes is on the `6-all-stats` branch.  I suggest building your changes off of that branch.
